travis:
  secure:
    BINSTAR_TOKEN: HdYK0JjQF9AO2qU/RKEOvHl/ycvcH5wnfK8krco17bFlLt8pz7xrKf5wgB4sqcjBJUleADmFTjRuf7cvVDqw98Qnpbovhaft3v/mt0Oabi2/fig1dVOeIo0L6cID8/p2N1HbWUCuvs06iZf2Znk1Qs6jxAVcBmVnqKorvnWlmdMykP/owIIq1FvVu5OPRO1Bgso4fgpWRF39O8cbr/n+15CwZGkqBijbHi1b0fgebOLmxTUDOKWqGgAwZBsZ8hz/OvvBaky/rOeZTNAI0b1/t+F9a43k3RAnya9bj+SFXoo0qUzGrhDue+g+yQvr2uaQhLq35DVZl9PRREAqfbYvvxftdCecY50U13RQgInIP8cDUY9NRSYfG7Cvmo66Ziv8hRgzzU0znefsV3PoBAdXrsqg5kRf64qNkn0IU9aId+1K7LgStrBvsJk9DTSQFRuCQMzqpSfyCuV0/SWDQhxoNYEFMdqhWJNmLV0mu9zs++Fcp5NwhVmoNF+fyTDzczQZaWcHrsr3lZUxeGD4kyxB2w3vRsZzSWE7ci3SENnmIfMyullAZpkAo5tBQEqNc6/cuFhmZ6rydZ2KUmgSdeA2a8Z7OPT28msO/XPEoD0wh64tbaFgjp2JPyCsjdQq8DXqwsq0UCDKLXMvqX4AFw2xFG/PcN/sGHQq9PFxsXOXHvk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
