travis:
  secure:
    BINSTAR_TOKEN: kl9tTV9KUFX0nHe6w4Oncuax7qDWyBSooeTA6nD1t15z1ktneVhbsmdpQ2hCksrkQUdQJZt/bFxSOUU4jYVLE6dPK5yJ0dxJxyfkLb+ZC95fM1lfpBBXTq1yK4YfzviDqLIIkk1RHTDq4jwzsNX+fhpWQgmuyaUhd5KrkwxLW/7Eb3PB8/yGuGnZDdquIThcy5AZEO4yJSf2woHY2l09hWcAAi2tlWXlkrTO6EF8vhCv3HNMgXW11XPE//FGXpNVscdHY8Iqrsm9hYzqPLZM+IxcH2q8CAFqIbzQKUBJbhQx4TDsBpMXlsFi5KDAZ7/COevIvRafdrw+2SujL5GT7z4D4u7SZUbBdhkHZqeiEfxLGAzwOepr4OU5i4dYNHTfzCIqMdlQhcLGq+yZjPx8N9uKKbslX+j85crB3GiukdZCwkc1oUeD2XqwWfqZI7CiUZu8djLqtAN86/PevBy+rgeCTU6ZCI56GL4ozP7wEuJaPv/wAYmU3UtNge4dF85KKR1yydKCO0Kq6s/+mKqkWd3b+q0qHk0oeSrvh89zMdy5el4Ztc8dFjsP24CG7OAUyW4iI+L3YD95weicO7vBTcTGPgY3OQfA2evF73PDgcDaZLAV6LyFBYSTe1oV8GR+wPwnfPrd0+rx+xrnmvNFNNZBTKXliI3VGNLKgVq1mwE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
